### ISSUE TITLE
Editing option after submission

### ISSUE THREAD

**Issue by ebtihaj-khan** [codeforpakistan/Disability-Certificate---One-Window-Operation#22] opened 2021-05-21 13:54 UTC
There can be a case where the staff submits incorrect data and wants to edit it again.

**Comment by ebtihaj-khan** [comment] 2021-05-21 16:04
#24

**Comment by ebtihaj-khan** [comment] 2021-06-01 10:00
Add comments and submit for reverification

**Comment by ebtihaj-khan** [comment] 2021-06-08 10:43
@laraibsahmed need to finalize a cutoff point for editing an application. Can possibly be after the generation of a certificate?

**Comment by laraibsahmed** [comment] 2021-06-22 06:58
once the application goes to board member, It shouldn't be updated/edited. 
FYI - @ebtihaj-khan @mubassirhayat @aliirz

**Comment by mubassirhayat** [comment] 2021-07-13 20:26
duplicate of #59

**Closed by mubassirhayat** 2021-07-13 20:26 UTC
Labels: enhancement, sprint 2
